<%@ Page Language="C#" AutoEventWireup="true" CodeFile="StoreSales.aspx.cs" Inherits="StoreSales" MasterPageFile="~/MasterPage.master" %>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
     <style>
        
        .aspNetHidden
        {
      display:none;

        }
        
div {
    width: 340px;
    padding: 25px;
    border: 18px solid #151414;
    margin: 15px;
    float: left;
    border-color:lightgreen;
}
body{
    background-color:lightgreen;
}

user agent stylesheet
div {
    display: block;
}
          .auto-style2 {
             width: 776px;
         }
          </style>
    <center>
    <h1 class="auto-style2">Store Sales Page</h1>
        <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
            SelectCommand="SELECT * FROM [store_sales]"
            UpdateCommand="UPDATE [store_sales] SET [StoreID]=@StoreID, [Year]=@Year, [Week]=@Week,[Sales]=@Sales WHERE [id]=@id "
            DeleteCommand="DELETE FROM [store_sales] WHERE [id]=@id"></asp:SqlDataSource>
            <input action="action" onclick="history.go(-1);" type="button" value="Back"/> 
            
</center>
    
        <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" CellPadding="4" DataKeyNames="ID" DataSourceID="SqlDataSource2" Width="1010px" Align="Center" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellSpacing="2" ForeColor="Black">
            <Columns>
                <asp:BoundField DataField="ID" HeaderText="ID" InsertVisible="False" ReadOnly="True" SortExpression="ID" />
                <asp:BoundField DataField="StoreID" HeaderText="StoreID" SortExpression="StoreID" />
                <asp:BoundField DataField="Year" HeaderText="Year" SortExpression="Year" />
                <asp:BoundField DataField="Week" HeaderText="Week" SortExpression="Week" />
                <asp:BoundField DataField="Sales" HeaderText="Sales" SortExpression="Sales" />
            </Columns>
            <FooterStyle BackColor="#CCCCCC" />
            <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Left" />
            <RowStyle BackColor="White" />
            <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#808080" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#383838" />
        </asp:GridView>
        </asp:Content>
