<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Users.aspx.cs" Inherits="Manager" MasterPageFile="~/MasterPage.master" %>


<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
     <style>
      
     body{

         background-color:gray;
         align-content:flex-start;
     }
        .aspNetHidden
        {
      display:none;

        }
         .auto-style2 {
             margin-right: 160px;
         }
    </style>
    <center>
        <h1>Users Page</h1>

         <input action="action" onclick="history.go(-1);" type="button" value="Back"/>
    </center>
        <asp:SqlDataSource ID="SqlDataSourceRegistration" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>"
            SelectCommand="SELECT * FROM [Registration]" 
            UpdateCommand="UPDATE [Registration] SET [FirstName]=@FirstName, [LastName]=@LastName, [UserName]=@UserName,[Email]=@Email, [Password]=@Password, [Country]=@Country WHERE [id]=@id "
            DeleteCommand="DELETE FROM [Registration] WHERE [id]=@id"></asp:SqlDataSource>
        <asp:GridView ID="GridView1"  runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" CellPadding="2" CellSpacing="2" DataKeyNames="Id" DataSourceID="SqlDataSourceRegistration" ForeColor="Black" Height="199px" Width="1247px" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CssClass="auto-style2">
            <Columns>
                <asp:BoundField DataField="Id" HeaderText="Id" ReadOnly="True" SortExpression="Id" />
                <asp:BoundField DataField="FirstName" HeaderText="FirstName" SortExpression="FirstName" />
                <asp:BoundField DataField="LastName" HeaderText="LastName" SortExpression="LastName" />
                <asp:BoundField DataField="UserName" HeaderText="UserName" SortExpression="UserName" />
                <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
                <asp:BoundField DataField="Password" HeaderText="Password" SortExpression="Password" />
                <asp:BoundField DataField="Country" HeaderText="Country" SortExpression="Country" />
            </Columns>
            <FooterStyle BackColor="#CCCCCC" />
            <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Left" />
            <RowStyle BackColor="White" />
            <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White"  />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#808080" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#383838" />
        </asp:GridView>
    
   </asp:Content>